# https://circleci.com/docs/reference-2-1/
# https://circleci.com/docs/2.0/workflows/
#
version: 2.1
jobs:
  build-and-test-node10:
    docker:
      - image: node:10

    working_directory: ~/tmp-node10

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Packages
          # `yarn.lock` enforcement, just like the Dockerfile
          command: >
            # allow ENV-driven `npm` token; CircleCI-only
            cp ~/tmp-node10/.npmrc /tmp/.npmrc;
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/tmp-node10/.npmrc;

            rm -f npm-shrinkwrap.json;
            yarn install --frozen-lockfile;

            # revert ENV-driven `npm` token
            cp /tmp/.npmrc ~/tmp-node10/.npmrc;

      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Build
          command: "yarn build"

      - run:
          name: Test Suite
          command: "yarn run test:ci"

      - persist_to_workspace:
          root: .
          paths:
            - .

  #
  # @see README.md + "Node 6 Support"
  #
  build-and-test-node6:
    docker:
      - image: node:6

    working_directory: ~/tmp-node6

    steps:
      - checkout

      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "npm-shrinkwrap.json" }}
          - npm-dependencies-

      - run:
          name: Install Packages
          # https://docs.npmjs.com/cli/install
          #   "If the package has a ... shrinkwrap file, the installation of dependencies will be driven by that."
          command: >
            # allow ENV-driven `npm` token; CircleCI-only
            cp ~/tmp-node10/.npmrc /tmp/.npmrc;
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/tmp-node10/.npmrc;

            rm -f yarn.lock;
            npm install;

            # revert ENV-driven `npm` token
            cp /tmp/.npmrc ~/tmp-node10/.npmrc;

      - save_cache:
          paths:
            - node_modules
          key: yarn-dependencies-{{ checksum "npm-shrinkwrap.json" }}

      - run:
          name: Build
          command: "npm run build"

      - run:
          name: Test Suite
          command: "npm run node6:test:ci"

      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test-node10:
          filters:
            tags:
              only: /.*/
      - build-and-test-node6:
          filters:
            tags:
              only: /.*/
